environment        = "production"
location           = "East US"
container_image    = "ghcr.io/vexardrive/fleet-ping-service:latest"
db_sku             = "GP_Standard_D2ds_v4"
db_storage_mb      = 262144
app_cpu            = 1.0
app_memory         = "2Gi"
app_min_replicas   = 2
app_max_replicas   = 20
log_retention_days = 90
alert_email        = "oncall@vexardrive.com"
